[2022-06-08 22:00:18,961] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: hello.get_name 2022-06-08T22:00:17.491082+00:00 [queued]>
[2022-06-08 22:00:18,979] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: hello.get_name 2022-06-08T22:00:17.491082+00:00 [queued]>
[2022-06-08 22:00:18,979] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-06-08 22:00:18,979] {taskinstance.py:1068} INFO - Starting attempt 1 of 2
[2022-06-08 22:00:18,981] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-06-08 22:00:18,991] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): get_name> on 2022-06-08T22:00:17.491082+00:00
[2022-06-08 22:00:18,997] {standard_task_runner.py:52} INFO - Started process 991 to run task
[2022-06-08 22:00:19,000] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'hello', 'get_name', '2022-06-08T22:00:17.491082+00:00', '--job-id', '43', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/username.py', '--cfg-path', '/tmp/tmpdxhj50ls', '--error-file', '/tmp/tmp7v2nc112']
[2022-06-08 22:00:19,001] {standard_task_runner.py:77} INFO - Job 43: Subtask get_name
[2022-06-08 22:00:19,040] {logging_mixin.py:104} INFO - Running <TaskInstance: hello.get_name 2022-06-08T22:00:17.491082+00:00 [running]> on host 69873a4b1233
[2022-06-08 22:00:19,099] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=hello
AIRFLOW_CTX_TASK_ID=get_name
AIRFLOW_CTX_EXECUTION_DATE=2022-06-08T22:00:17.491082+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-08T22:00:17.491082+00:00
[2022-06-08 22:00:19,100] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-06-08 22:00:19,101] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'echo Alma > ./cr_ch6/dags/username.txt']
[2022-06-08 22:00:19,110] {subprocess.py:75} INFO - Output:
[2022-06-08 22:00:19,114] {subprocess.py:79} INFO - bash: ./cr_ch6/dags/username.txt: No such file or directory
[2022-06-08 22:00:19,114] {subprocess.py:83} INFO - Command exited with return code 1
[2022-06-08 22:00:19,131] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-06-08 22:00:19,134] {taskinstance.py:1531} INFO - Marking task as UP_FOR_RETRY. dag_id=hello, task_id=get_name, execution_date=20220608T220017, start_date=20220608T220018, end_date=20220608T220019
[2022-06-08 22:00:19,212] {local_task_job.py:151} INFO - Task exited with return code 1
