[2022-06-08 22:08:40,335] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: hello.get_name 2022-06-08T22:00:17.491082+00:00 [queued]>
[2022-06-08 22:08:40,355] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: hello.get_name 2022-06-08T22:00:17.491082+00:00 [queued]>
[2022-06-08 22:08:40,356] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-06-08 22:08:40,356] {taskinstance.py:1068} INFO - Starting attempt 3 of 3
[2022-06-08 22:08:40,358] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-06-08 22:08:40,367] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): get_name> on 2022-06-08T22:00:17.491082+00:00
[2022-06-08 22:08:40,373] {standard_task_runner.py:52} INFO - Started process 1466 to run task
[2022-06-08 22:08:40,377] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'hello', 'get_name', '2022-06-08T22:00:17.491082+00:00', '--job-id', '45', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/username.py', '--cfg-path', '/tmp/tmppwucifjc', '--error-file', '/tmp/tmppl56n1k9']
[2022-06-08 22:08:40,377] {standard_task_runner.py:77} INFO - Job 45: Subtask get_name
[2022-06-08 22:08:40,418] {logging_mixin.py:104} INFO - Running <TaskInstance: hello.get_name 2022-06-08T22:00:17.491082+00:00 [running]> on host 69873a4b1233
[2022-06-08 22:08:40,478] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=hello
AIRFLOW_CTX_TASK_ID=get_name
AIRFLOW_CTX_EXECUTION_DATE=2022-06-08T22:00:17.491082+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-08T22:00:17.491082+00:00
[2022-06-08 22:08:40,479] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-06-08 22:08:40,479] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'echo Alma > ./cr_ch6/dags/username.txt']
[2022-06-08 22:08:40,487] {subprocess.py:75} INFO - Output:
[2022-06-08 22:08:40,489] {subprocess.py:79} INFO - bash: ./cr_ch6/dags/username.txt: No such file or directory
[2022-06-08 22:08:40,489] {subprocess.py:83} INFO - Command exited with return code 1
[2022-06-08 22:08:40,500] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-06-08 22:08:40,502] {taskinstance.py:1531} INFO - Marking task as FAILED. dag_id=hello, task_id=get_name, execution_date=20220608T220017, start_date=20220608T220840, end_date=20220608T220840
[2022-06-08 22:08:40,551] {local_task_job.py:151} INFO - Task exited with return code 1
